name: Generate index.html

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write   # Needed so the action can push changes to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate index.html
        run: |
          # 1. Create the skeleton of our index.html
          echo "<!DOCTYPE html>" > index.html
          echo "<html>" >> index.html
          echo "<head>" >> index.html
          echo "  <meta charset='utf-8' />" >> index.html
          echo "  <title>Repo File Index</title>" >> index.html
          echo "</head>" >> index.html
          echo "<body>" >> index.html
          echo "  <h1>List of HTML Files in This Repo</h1>" >> index.html
          echo "  <ul>" >> index.html

          # 2. Find all .html files (except index.html itself)
          #    Also ignoring anything in .github just to be safe
          #    Adjust the find command as needed.
          for file in $(find . -type f -name '*.html' ! -path './.github/*' ! -name 'index.html' | sort); do
            # Remove leading "./" for the link
            short_path="${file#./}"
            echo "    <li><a href=\"$short_path\">$short_path</a></li>" >> index.html
          done

          echo "  </ul>" >> index.html
          echo "</body>" >> index.html
          echo "</html>" >> index.html

      - name: Commit and push changes
        run: |
          # Only commit/push if index.html changed
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add index.html
            git commit -m "Auto-generate index.html [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
